version: '3.9'
services:
  airflow:
    image: apache/airflow:2.10.0
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"